#!/usr/bin/env bash
# Find and kill the 7-highlander process with SIGKILL

pid=$(ps aux | grep '[7]\-highlander' | awk '{print $2}')

if [ -n "$pid" ]; then
    kill -9 "$pid"
    echo "OK"
else
    echo "7-highlander not running"
fi
