#!/usr/bin/env bash
# Kill all 7-highlander processes using SIGKILL

pids=$(pgrep -f 7-highlander)

if [ -n "$pids" ]; then
    for pid in $pids; do
        kill -9 "$pid"
    done
    echo "OK"
else
    echo "7-highlander not running"
fi
