#!/usr/bin/env bash
# This script displays "Best School" 10 times, with "Hi" on a new line at the 9th iteration using a while loop and if statement

count=1
while [ $count -le 10 ]
do
    echo "Best School"
    if [ $count -eq 9 ]
    then
        echo "Hi"
    fi
    ((count++))
done
