#!/usr/bin/env bash
# This script loops from 1 to 10, displaying 'bad luck' on the 4th iteration (unlucky in Chinese culture due to its phonetic similarity to 'death'), 'good luck' on the 8th iteration (lucky due to its similarity to 'wealth'), and 'Best School' for others.

counter=1

while [ $counter -le 10 ]
do
    if [ $counter -eq 4 ]
    then
        echo "bad luck"
    elif [ $counter -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((counter++))
done
