#!/usr/bin/env bash
# This script loops from 1 to 20 using a while loop and case statement, displaying numbers and specific 'bad luck' messages for iterations 4 (China), 9 (Japan), and 17 (Italy).

counter=1

while [ $counter -le 20 ]
do
    case $counter in
        4)
            echo "4"
            echo "bad luck from China"
            ;;
        9)
            echo "9"
            echo "bad luck from Japan"
            ;;
        17)
            echo "17"
            echo "bad luck from Italy"
            ;;
        *)
            echo $counter
            ;;
    esac
    ((counter++))
done
